// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetQRpath() {
  return window['go']['main']['App']['GetQRpath']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Logger(arg1) {
  return window['go']['main']['App']['Logger'](arg1);
}

export function LoginCode() {
  return window['go']['main']['App']['LoginCode']();
}
