// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetQRpath():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Logger(arg1:any):Promise<void>;

export function LoginCode():Promise<void>;
